<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>LevelUp.Bifrost.Core</PackageId>
    <RootNamespace>Bifrost.Core</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- NativeAOT compatibility -->
    <IsAotCompatible>true</IsAotCompatible>
    <!-- Generate documentation -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
