<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1822</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bifrost\Bifrost.csproj" />
    <ProjectReference Include="..\Bifrost.Concurrency\Bifrost.Concurrency.csproj" />
    <ProjectReference Include="..\Bifrost.HealthChecks\Bifrost.HealthChecks.csproj" />
    <ProjectReference Include="..\Bifrost.Resilience\Bifrost.Resilience.csproj" />
    <ProjectReference Include="..\Bifrost.Scheduling\Bifrost.Scheduling.csproj" />
    <ProjectReference Include="..\Bifrost.Scheduling.Core\Bifrost.Scheduling.Core.csproj" />
  </ItemGroup>

</Project>
