<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Bifrost.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- Tests don't need to be AOT compatible -->
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bifrost.Core\Bifrost.Core.csproj" />
    <ProjectReference Include="..\Bifrost.HealthChecks\Bifrost.HealthChecks.csproj" />
    <ProjectReference Include="..\Bifrost.OpenTelemetry\Bifrost.OpenTelemetry.csproj" />
    <ProjectReference Include="..\Bifrost.Resilience\Bifrost.Resilience.csproj" />
    <ProjectReference Include="..\Bifrost\Bifrost.csproj" />
  </ItemGroup>

</Project>
